[fuel_cell_a]
serial.port = "/dev/tty_FCA"
serial.baudrate = 57600

[fuel_cell_b]
serial.port = "/dev/tty_FCB"
serial.baudrate = 57600

# TODO: check channels
[high_pressure_manometer]
channel = 0
max_bar = 400
max_delta = 20

[low_pressure_manometer]
channel = 1
max_bar = 4
max_delta = 0.05

# TODO: check pins and NO / NC + rename
[valve1]
control_pin = 8
error_pin = 9
normally_open = false

[valve2]
control_pin = 0
error_pin = 0
normally_open = true

[[temperatures]]
name = "H2Plate"
address = 0x00000dc67e14
warn = 0
alert = 0
max = 0

[[temperatures]]
name = "Batteries"
address = 0x00000e841698
warn = 0
alert = 0
max = 0

[[temperatures]]
name = "FuelCellControllers"
address = 0xFFFFFFFFFFFF
warn = 0
alert = 0
max = 0

[[temperatures]]
name = "H2Tanks"
address = 0xFFFFFFFFFFFF
warn = 0
alert = 0
max = 0

[[temperatures]]
name = "Extra"
address = 0x00000dc6d911
warn = 100
alert = 105
max = 200

[battery_gauge]
i2c_address = 0x64

[accelerometer]
i2c_address = 0x53

[gyroscope]
i2c_address = 0x68

[compass]
i2c_address = 0x0C

[gps]
serial.port = "/dev/serial0"
serial.baudrate = 9600

[start_button]
pin = 0

[stop_button]
pin = 0

[telemetry]
serial.port = ""
serial.baudrate = 0
send_interval = 0
token_path = "$HOME/boat_token.txt"
