[fuel_cell_a]
serial.port = "/dev/tty_FCA"
serial.baudrate = 57600
warn_temperature = 52
alert_temperature = 59
critical_temperature = 66

[fuel_cell_b]
serial.port = "/dev/tty_FCB"
serial.baudrate = 57600
warn_temperature = 52
alert_temperature = 59
critical_temperature = 66

[high_pressure_manometer]
channel = 0
max_bar = 400
max_delta = 20
warn_pressure = 240
alert_pressure = 270
critical_pressure = 300

[low_pressure_manometer]
channel = 1
max_bar = 4
max_delta = 0.05
warn_pressure = 0.65
alert_pressure = 0.68
critical_pressure = 0.71

[valve1]
control_pin = 8
error_pin = 9
normally_open = false

[valve2]
control_pin = 0
error_pin = 0
normally_open = true

[[temperatures]]
name = "H2Plate"
address = 0x00000dc67e14
warn = 64
alert = 72
critical = 80

[[temperatures]]
name = "Batteries"
address = 0x00000e841698
warn = 48
alert = 54
critical = 60

[[temperatures]]
name = "FuelCellControllers"
address = 0x00000dc75129
warn = 64
alert = 72
critical = 80

[[temperatures]]
name = "H2Tanks"
address = 0x00000dc6d911
warn = 48
alert = 54
critical = 60

[battery_gauge]
i2c_address = 0x64
warn_level = 40
alert_level = 20
critical_level = 10

[accelerometer]
i2c_address = 0x53

[gyroscope]
i2c_address = 0x68

[compass]
i2c_address = 0x0C

[gps]
serial.port = "/dev/serial0"
serial.baudrate = 9600

[start_button]
pin = 0

[stop_button]
pin = 0

[telemetry]
serial.port = "/dev/ttyACM0"
serial.baudrate = 0
send_interval = 1
token_path = "$HOME/boat_token.txt"

[fca_relay]
pin = 0
normally_open = true

[fcb_relay]
pin = 0
normally_open = true

[source_isolation_contactor]
pin = 0
normally_open = true

[level2_charge_contactor]
pin = 0
normally_open = true
